<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use Illuminate\Http\Request;

class BukuController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'role:mahasiswa']);
    }

    /**
     * Tampilkan semua buku
     */
    public function index(Request $request)
    {
        $query = Buku::query();

        // Fitur pencarian
        if ($request->filled('search')) {
            $search = $request->search;
            $query->where('judul', 'like', "%{$search}%")
                ->orWhere('penulis', 'like', "%{$search}%")
                ->orWhere('penerbit', 'like', "%{$search}%");
        }

        // Filter berdasarkan kategori (jurusan kuliah)
        if ($request->filled('kategori')) {
            $query->where('kategori', $request->kategori);
        }

        // Urutkan dari terbaru
        $buku = $query->orderBy('created_at', 'desc')->paginate(8);

        // Daftar semua kategori jurusan kuliah (diambil dari daftar umum jurusan di Indonesia)
        $categories = [
            'Aktuaria',
            'Astronomi',
            'Biologi',
            'Bioteknologi',
            'Fisika',
            'Geofisika',
            'Geologi',
            'Ilmu Lingkungan',
            'Kimia',
            'Matematika',
            'Matematika Bisnis',
            'Meteorologi',
            'Statistika',
            'Apoteker',
            'Farmasi',
            'Fisioterapi',
            'Ilmu Gizi',
            'Ilmu Kedokteran',
            'Ilmu Keperawatan',
            'Kebidanan',
            'Kedokteran Gigi',
            'Kedokteran Hewan',
            'Kesehatan Lingkungan',
            'Kesehatan Masyarakat',
            'Keselamatan dan Kesehatan Kerja',
            'Pendidikan Dokter',
            'Psikologi',
            'Rekam Medis',
            'Ilmu Teknik',
            'Instrumentasi',
            'Pendidikan Teknologi Agroindustri',
            'Rekayasa Keselamatan Kebakaran',
            'Teknik Biomedis',
            'Teknik Dirgantara/Penerbangan',
            'Teknik Elektro',
            'Teknik Geodesi',
            'Teknik Geomatika',
            'Teknik Geologi',
            'Teknik Industri',
            'Teknik Kimia',
            'Teknik Listrik',
            'Teknik Material',
            'Teknik Mesin',
            'Teknik Metalurgi',
            'Teknik Nuklir',
            'Teknik Otomotif',
            'Teknik Penerbangan',
            'Teknik Perkapalan',
            'Teknik Perminyakan',
            'Teknik Pertambangan',
            'Teknik Robotika',
            'Teknologi Bioproses',
            'Cyber Security',
            'Ilmu Komputer',
            'Manajemen Informatika',
            'Sains Data',
            'Sistem Informasi',
            'Sistem Komputer',
            'Teknik Komputer',
            'Teknik Telekomunikasi',
            'Teknologi Informasi',
            'Teknologi Rekayasa Multimedia',
            'Arsitektur Interior',
            'Arsitektur Lanskap',
            'Konstruksi',
            'Perencanaan Wilayah dan Kota',
            'Teknik Arsitektur',
            'Teknik Bangunan',
            'Teknik Lingkungan',
            'Teknik Pengairan',
            'Teknik Sipil',
            'Agribisnis',
            'Agriekoteknologi',
            'Agrobisnis Perikanan',
            'Agronomi dan Hortikultura',
            'Akuakultur',
            'Bioteknologi',
            'Ilmu Kelautan',
            'Ilmu Perikanan',
            'Kehutanan',
            'Kelautan',
            'Manajemen Sumber Daya Perairan',
            'Manajemen Sumberdaya Lahan',
            'Nautika',
            'Oseanografi',
            'Pertanian dan Agribisnis',
            'Peternakan',
            'Proteksi Tanaman',
            'Teknik Kelautan',
            'Teknik Pertanian',
            'Teknologi Industri Pertanian',
            'Teknologi Pangan',
            'Ilmu Olahraga',
            'Administrasi Bisnis/Tata Niaga',
            'Administrasi Pemerintahan',
            'Administrasi Perkantoran',
            'Administrasi Publik',
            'Antropologi Sosial/Budaya',
            'Arkeologi',
            'Hubungan Internasional',
            'Ilmu Administrasi Fiskal',
            'Ilmu Administrasi Negara',
            'Ilmu Administrasi Niaga',
            'Ilmu Pemerintahan',
            'Ilmu Politik',
            'Kesejahteraan Sosial',
            'Kriminologi',
            'Sejarah',
            'Sosiologi',
            'Hubungan Masyarakat',
            'Ilmu Komunikasi',
            'Ilmu Perpustakaan',
            'Jurnalistik',
            'Kearsipan Digital',
            'Komunikasi dan Pengembangan Masyarakat',
            'Manajemen Komunikasi',
            'Televisi dan Film',
            'Bahasa dan Budaya Tiongkok',
            'Bahasa dan Kebudayaan Korea',
            'Ilmu Filsafat',
            'Linguistik',
            'Sastra Arab',
            'Sastra Belanda',
            'Sastra Cina',
            'Sastra Indonesia',
            'Sastra Inggris',
            'Sastra Jawa',
            'Sastra Sunda',
            'Sastra Daerah',
            'Sastra Jepang',
            'Sastra Jerman',
            'Sastra Prancis',
            'Sastra Rusia/Slavia',
            'Sejarah dan Kebudayaan Islam',
            'Akuntansi',
            'Bisnis Digital',
            'Bisnis Internasional',
            'Bisnis Islam',
            'Ekonomi Pembangunan',
            'Ekonomi Syariah',
            'Hubungan Masyarakat',
            'Ilmu Ekonomi',
            'Ilmu Ekonomi Islam',
            'Kewirausahaan',
            'Manajemen',
            'Manajemen Bisnis',
            'Manajemen Keuangan',
            'Perbankan',
            'Geografi',
            'Ilmu Hukum',
            'Ilmu Keluarga dan Konsumen',
            'Ilmu Kesejahteraan Sosial',
            'Manajemen Perhotelan',
            'Pariwisata',
            'Peradilan Agama',
            'Perhotelan',
            'Politik Islam',
            'Psikologi',
            'Studi Agama',
            'Teologi',
            'Travel',
            'Administrasi Pendidikan',
            'Bimbingan dan Konseling',
            'Manajemen Pemasaran Pariwisata',
            'Manajemen Pendidikan',
            'Pendidikan Agama Islam',
            'Pendidikan Bahasa Arab',
            'Pendidikan Bahasa Daerah',
            'Pendidikan Bahasa Indonesia',
            'Pendidikan Bahasa Inggris',
            'Pendidikan Bahasa Jepang',
            'Pendidikan Bahasa Jerman',
            'Pendidikan Bahasa Korea',
            'Pendidikan Bahasa Prancis',
            'Pendidikan Biologi',
            'Pendidikan Fisika',
            'Pendidikan Geografi',
            'Pendidikan Guru Anak Usia Dini (PAUD)',
            'Pendidikan Guru Sekolah Dasar (PGSD)',
            'Pendidikan Ilmu Komputer',
            'Pendidikan IPA',
            'Pendidikan IPS',
            'Pendidikan Jasmani, Kesehatan, dan Rekreasi',
            'Pendidikan Kepelatihan Olahraga',
            'Pendidikan Khusus',
            'Pendidikan Kimia',
            'Pendidikan Luar Biasa',
            'Pendidikan Luar Sekolah (PLS)',
            'Pendidikan Masyarakat',
            'Pendidikan Matematika',
            'Pendidikan Pancasila dan Kewarganegaraan',
            'Pendidikan Sejarah',
            'Pendidikan Seni Musik',
            'Pendidikan Seni Rupa',
            'Pendidikan Seni Tari',
            'Pendidikan Sosiologi',
            'Pendidikan Teknik Otomotif',
            'Perpustakaan & Sains Informasi',
            'Psikologi Pendidikan dan Bimbingan',
            'Teknologi Pendidikan',
            'Desain dan Komunikasi Visual',
            'Desain Interior',
            'Desain Produk',
            'Film dan Animasi',
            'Film dan Televisi',
            'Musik',
            'Seni Kriya',
            'Seni Musik',
            'Seni Rupa Murni',
            'Seni Tari',
            'Tata Boga',
            'Tata Busana',
            'Tata Kelola Seni',
            'Tata Rias',
            'Administrasi Asuransi Dan Aktuaria',
            'Administrasi Bisnis',
            'Administrasi Keuangan Dan Perbankan',
            'Administrasi Perkantoran Dan Sekretaris',
            'Administrasi Perpajakan',
            'Administrasi Perumahsakitan',
            'Akuntansi',
            'Akuntansi Perpajakan',
            'Akuntansi Sektor Publik',
            'Analisis Kimia',
            'Bisnis Internasional',
            'Desain Batik Dan Fashion',
            'Desain Grafis',
            'Ekowisata',
            'Fisioterapi',
            'Hubungan Masyarakat',
            'Informasi Dan Humas',
            'Instrumentasi Dan Elektronika',
            'Kearsipan',
            'Manajemen Informasi Dan Dokumentasi',
            'Manajemen Perhotelan',
            'Okupasi Terapi',
            'Paramedik Veteriner',
            'Pemasaran Digital',
            'Penyiaran Multimedia',
            'Periklanan Kreatif',
            'Sekretaris',
            'Teknologi Produksi',
            'Vokasional Pariwisata'
        ];

        return view('mahasiswa.buku.index', compact('buku', 'categories'));
    }

    /**
     * Tampilkan detail satu buku
     */
    public function show($id)
    {
        $buku = Buku::findOrFail($id);
        return view('mahasiswa.buku.show', compact('buku'));
    }
}